### ISSUE TITLE
Normalize naming conventions across the API

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#95] opened 2022-07-28 19:24 UTC
In the manifest we have fields such as `identifierSpace` and `feature_view`.
We should settle on a style: either `identifierSpace` and `featureView`, or `identifier_space` and `feature_view`.

I think in JSON it is somehow more common to have `feature_view` than `featureView`.

**Comment by thadguidry** [comment] 2022-07-28 20:19
Agree, underscore separation

**Comment by wetneb** [comment] 2022-07-29 04:48
Yeah but on the other side, the `identifierSpace` and `schemaSpace` have been there for ages, whereas `feature_view`, so it would likely be much less disruptive to rename the latter…

**Comment by fsteeg** [comment] 2024-07-11 11:21
Resolved with #166 (PR for #150, which was a duplicate of this), closing.

**Closed by fsteeg** 2024-07-11 11:21 UTC
